#!/usr/bin/env python3
"""tools/wii/make-splash-blob.py -- build the Wii boot-splash compressed blob.

Build-time pipeline for the Wii boot-splash "compressed-transient" model (see
src/platform/wii/SplashBootScreen.cpp): rather than embedding the full
1024x1024 GXT1 logo texture (2 MB tiled) and cropping it at draw time, this
script pre-crops and pre-downscales the source to exactly the on-screen
result -- StartupEffects.cpp DrawStartFade()'s frame-0 UV crop
(uMin=0.03125, uMax=0.96875, vMin=0.1875, vMax=0.8125) drawn at 480x320 -- so
the embedded/inflated data is display-native and much smaller.

Pipeline, pure stdlib (reuses tools/lib/tex_decoder.py + tools/lib/gx_encoder.py,
both already dependency-free):
  1. Decode the ORIGINAL Tex1 source (FruitNinjaBada/Data/textures/hb_logo.tex,
     format 0x10 RGBA4444, 1024x1024) to linear RGBA8888. This is the same
     source stage-assets.py itself decodes for the host/web WebP path, so
     starting here (not un-tiling the staged Wii GXT1) needs no new decode
     logic and matches the pre-tiling source of truth.
  2. Crop to the visible region only: cols [32,992) rows [192,832) = 960x640
     -- exactly the UV crop above (32/1024=0.03125 etc.), so the runtime quad
     no longer needs to sub-rect sample.
  3. Downscale 960x640 -> 480x320 by an exact 2x2 box average (480 and 320
     are both multiples of 4, so the result tiles cleanly for GX_TF_RGB5A3).
  4. RGB5A3-encode + GX-tile via tools/lib/gx_encoder.py (same encoder
     stage-assets.py --wii uses for every other texture) -- no GXT1 header,
     just the raw tiled payload, since the runtime buffer is fed straight to
     GX_InitTexObj with a compile-time-known width/height/format.
  5. Raw-DEFLATE compress (see deflate-blob.py's deflate_raw) for embedding.

Output is a generated C++ source (not a raw .bin for .incbin) -- see
src/platform/wii/CMakeLists.txt: the devkitPPC CMake toolchain wrapper
(cmake/wii.toolchain.cmake) delegates to devkitPro's Wii.cmake, which only
wires up CMake's CXX language (not C, not ASM), so neither a `.c` TU nor a
`.s` + `.incbin` TU can be compiled -- everything is built as C++. The byte
array is plain C-compatible syntax, so it compiles unchanged as C++; its
globals are declared `extern "C"` so SplashBootScreen.cpp's `extern "C"`
consumer declarations resolve (a namespace-scope `const` otherwise defaults
to internal linkage in C++, which would make the symbol invisible to the
linker).

Usage: make-splash-blob.py <hb_logo.tex source path> <output .cpp path>
"""

import sys
import zlib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "lib"))
from tex_decoder import decode_tex          # noqa: E402
from gx_encoder import encode_gxtx, GX_TF_RGB5A3  # noqa: E402

CROP_X0, CROP_Y0, CROP_X1, CROP_Y1 = 32, 192, 992, 832  # 960x640
OUT_W, OUT_H = 480, 320


def crop(rgba, w, x0, y0, x1, y1):
    cw, ch = x1 - x0, y1 - y0
    out = bytearray(cw * ch * 4)
    for y in range(ch):
        srow = ((y0 + y) * w + x0) * 4
        drow = y * cw * 4
        out[drow:drow + cw * 4] = rgba[srow:srow + cw * 4]
    return out, cw, ch


def downscale_2x2_box(rgba, w, h):
    """Exact 2x2 box average. w and h must be even."""
    assert w % 2 == 0 and h % 2 == 0
    ow, oh = w // 2, h // 2
    out = bytearray(ow * oh * 4)
    for y in range(oh):
        r0 = (2 * y) * w * 4
        r1 = (2 * y + 1) * w * 4
        drow = y * ow * 4
        for x in range(ow):
            i0 = r0 + 2 * x * 4
            i1 = r1 + 2 * x * 4
            for c in range(4):
                out[drow + x * 4 + c] = (
                    rgba[i0 + c] + rgba[i0 + 4 + c] + rgba[i1 + c] + rgba[i1 + 4 + c]
                ) // 4
    return bytes(out)


def deflate_raw(data):
    co = zlib.compressobj(9, zlib.DEFLATED, -15)
    return co.compress(data) + co.flush()


def emit_c_array(data, out_path):
    """Write a generated C++ source defining the compressed blob as a byte array.

    extern "C" linkage on both globals: a namespace-scope `const` defaults to
    internal linkage in C++ (unlike C), so without this the symbols wouldn't
    be visible to the linker at all -- SplashBootScreen.cpp's `extern "C"
    const unsigned char hb_logo_gxtx_z[];` declarations need a matching
    extern "C" definition here to resolve.
    """
    lines = []
    lines.append("// Auto-generated by tools/wii/make-splash-blob.py -- do not edit.")
    lines.append("")
    lines.append('extern "C" const unsigned char hb_logo_gxtx_z[] = {')
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x{:02x}".format(b) for b in chunk) + ",")
    lines.append("};")
    lines.append('extern "C" const unsigned int hb_logo_gxtx_z_len = {}u;'.format(len(data)))
    lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main(argv):
    if len(argv) != 3:
        print("usage: make-splash-blob.py <hb_logo.tex source> <output .c>", file=sys.stderr)
        return 2
    src_path, out_path = argv[1], argv[2]

    decoded = decode_tex(src_path)
    if decoded is None:
        print("make-splash-blob: {} did not parse as a known Tex1 format".format(src_path),
              file=sys.stderr)
        return 1
    w, h, rgba = decoded

    cropped, cw, ch = crop(rgba, w, CROP_X0, CROP_Y0, CROP_X1, CROP_Y1)
    assert (cw, ch) == (960, 640), (cw, ch)

    downscaled = downscale_2x2_box(cropped, cw, ch)
    assert len(downscaled) == OUT_W * OUT_H * 4

    tiled = encode_gxtx(downscaled, OUT_W, OUT_H, GX_TF_RGB5A3)[12:]  # strip GXT1 header
    assert len(tiled) == OUT_W * OUT_H * 2, len(tiled)  # RGB5A3 = 2 bytes/texel, no padding at these dims

    compressed = deflate_raw(tiled)

    emit_c_array(compressed, out_path)

    print("make-splash-blob: {} ({}x{}) -> {} ({}x{} RGB5A3) -> {} bytes tiled -> {} bytes compressed ({:.1f}%)".format(
        src_path, w, h, out_path, OUT_W, OUT_H, len(tiled), len(compressed),
        100.0 * len(compressed) / len(tiled)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
