#include "render/gl_funcs.h"

// Define all function pointers
#define GL_FUNC(ret, name, ...) PFN_##name name = nullptr;

GL_FUNC(const GLubyte*, glGetString, GLenum)
GL_FUNC(GLenum, glGetError, void)
GL_FUNC(void, glViewport, GLint, GLint, GLsizei, GLsizei)
GL_FUNC(void, glClearColor, GLfloat, GLfloat, GLfloat, GLfloat)
GL_FUNC(void, glClear, GLbitfield)
GL_FUNC(void, glEnable, GLenum)
GL_FUNC(void, glDisable, GLenum)
GL_FUNC(void, glBlendFunc, GLenum, GLenum)
GL_FUNC(void, glScissor, GLint, GLint, GLsizei, GLsizei)
GL_FUNC(void, glPixelStorei, GLenum, GLint)
GL_FUNC(void, glGenTextures, GLsizei, GLuint*)
GL_FUNC(void, glDeleteTextures, GLsizei, const GLuint*)
GL_FUNC(void, glBindTexture, GLenum, GLuint)
GL_FUNC(void, glTexParameteri, GLenum, GLenum, GLint)
GL_FUNC(void, glTexImage2D, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void*)
GL_FUNC(void, glCompressedTexImage2D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const void*)
GL_FUNC(void, glActiveTexture, GLenum)
GL_FUNC(void, glDrawArrays, GLenum, GLint, GLsizei)
GL_FUNC(void, glGenBuffers, GLsizei, GLuint*)
GL_FUNC(void, glDeleteBuffers, GLsizei, const GLuint*)
GL_FUNC(void, glBindBuffer, GLenum, GLuint)
GL_FUNC(void, glBufferData, GLenum, GLsizeiptr, const void*, GLenum)
GL_FUNC(void, glDrawElements, GLenum, GLsizei, GLenum, const void*)
GL_FUNC(void, glDepthFunc, GLenum)
GL_FUNC(void, glDepthMask, GLboolean)
GL_FUNC(void, glClearDepthf, GLfloat)

GL_FUNC(void, glMatrixMode, GLenum)
GL_FUNC(void, glPushMatrix, void)
GL_FUNC(void, glPopMatrix, void)
GL_FUNC(void, glLoadMatrixf, const GLfloat*)
GL_FUNC(void, glMultMatrixf, const GLfloat*)
GL_FUNC(void, glLoadIdentity, void)
GL_FUNC(void, glFrustumf, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat, GLfloat)
GL_FUNC(void, glEnableClientState, GLenum)
GL_FUNC(void, glDisableClientState, GLenum)
GL_FUNC(void, glVertexPointer, GLint, GLenum, GLsizei, const void*)
GL_FUNC(void, glNormalPointer, GLenum, GLsizei, const void*)
GL_FUNC(void, glColorPointer, GLint, GLenum, GLsizei, const void*)
GL_FUNC(void, glTexCoordPointer, GLint, GLenum, GLsizei, const void*)
GL_FUNC(void, glClientActiveTexture, GLenum)
GL_FUNC(void, glColor4ub, GLubyte, GLubyte, GLubyte, GLubyte)
GL_FUNC(void, glMaterialfv, GLenum, GLenum, const GLfloat*)
GL_FUNC(void, glLightfv, GLenum, GLenum, const GLfloat*)
GL_FUNC(void, glShadeModel, GLenum)
GL_FUNC(void, glTexEnvf, GLenum, GLenum, GLfloat)

#undef GL_FUNC

bool gl_load_functions() {
#define LOAD(name) \
    name = (PFN_##name)SDL_GL_GetProcAddress(#name); \
    if (!name) { fprintf(stderr, "Failed to load GL function: %s\n", #name); return false; }

    LOAD(glGetString)
    LOAD(glGetError)
    LOAD(glViewport)
    LOAD(glClearColor)
    LOAD(glClear)
    LOAD(glEnable)
    LOAD(glDisable)
    LOAD(glBlendFunc)
    LOAD(glScissor)
    LOAD(glPixelStorei)
    LOAD(glGenTextures)
    LOAD(glDeleteTextures)
    LOAD(glBindTexture)
    LOAD(glTexParameteri)
    LOAD(glTexImage2D)
    LOAD(glCompressedTexImage2D)
    LOAD(glActiveTexture)
    LOAD(glDrawArrays)
    LOAD(glGenBuffers)
    LOAD(glDeleteBuffers)
    LOAD(glBindBuffer)
    LOAD(glBufferData)
    LOAD(glDrawElements)
    LOAD(glDepthFunc)
    LOAD(glDepthMask)
    LOAD(glClearDepthf)

    LOAD(glMatrixMode)
    LOAD(glPushMatrix)
    LOAD(glPopMatrix)
    LOAD(glLoadMatrixf)
    LOAD(glMultMatrixf)
    LOAD(glLoadIdentity)
    LOAD(glFrustumf)
    LOAD(glEnableClientState)
    LOAD(glDisableClientState)
    LOAD(glVertexPointer)
    LOAD(glNormalPointer)
    LOAD(glColorPointer)
    LOAD(glTexCoordPointer)
    LOAD(glClientActiveTexture)
    LOAD(glColor4ub)
    LOAD(glMaterialfv)
    LOAD(glLightfv)
    LOAD(glShadeModel)
    LOAD(glTexEnvf)

#undef LOAD
    return true;
}
