// StructDefinitions.java - NOT a runnable script, reference only
// Recovered struct layouts for FruitNinja.exe (ARM32 ELF, Samsung Bada)
// Generated by RE session via GhidraMCP
//
// ============================================================
// FruitNinja  (size: 0x48 = 72 bytes)
// ============================================================
// Inherits: Osp::App::Application, IScreenEventListener, ITimerEventListener
//
// +0x00  void**                    vtable
// ????   IScreenEventListener      screenEventListener   (vtable @ vt+0x58)
// ????   ITimerEventListener       timerEventListener    (vtable @ vt+0x70)
// ????   GlesForm*                 mGlesForm
// ????   void*                     eglDisplay
// ????   EGLSurface                eglWindowSurface
// ????   void*                     eglConfig
// ????   EGLContext                eglContext
// +0x24  int                       field_0x24            (init=0)
// +0x28  int                       eglSurface            (int handle)
// +0x30  int                       field_0x30            (init=0)
// +0x34  int                       field_0x34            (init=0)
// +0x38  int                       field_0x38            (this-adj base for ITimerEventListener thunk)
// +0x3c  int                       field_0x3c            (init=0)
// +0x40  Osp::Base::Runtime::Timer* mTimer               (10ms = 100Hz game tick)
//
// Game loop: OnTimerExpired -> Timer::Start(10ms) + Draw()
// Draw() order: MAMAudioThread::ThreadMainLoop, MAMAudioController::Update,
//               sglMakeCurrent, glClear, SystemManager::Update,
//               game->Update(dt), BeginFrame, game->Draw(dt), EndFrame,
//               SwapBuffers, glFlush/glFinish, sglSwapBuffers,
//               Touch::Update, SoundManager::Update
// Terminates if frame stall counter > 90
//
// ============================================================
// GlesForm  (size: 0x1f8 = 504 bytes)
// ============================================================
// Inherits: Osp::Ui::Controls::Form
//
// +0x000  Form                      super                (0x1c8 = 456 bytes of Bada Form)
// +0x1c8  ITouchEventListener       touchListener        (vtable ptr)
// +0x1cc  IKeyEventListener         keyListener          (vtable ptr)
// +0x1d0  FruitNinja*               mpApp                (back-pointer to app)
// +0x1d4  uint                      touchIds[8]          (Bada touch point IDs, max 8 fingers)
// +0x1f4  int                       isReady              (=1 after ctor)
//
// Screen: 320x480 portrait. TransformTouchPos: y = 319 - scaled_y
// Touch pipeline: OnTouchMoved/Pressed/Released -> TransformTouchPos -> Mortar::Touch::__UpdateInternal
//
// ============================================================
// Game  (size: >= 0x5b2 bytes, singleton)
// ============================================================
// +0x00   void*                     vtable
// +0x04   char                      gameMode             (loaded from FruitSaveData[+0x6c])
// +0x14   char                      comboCounter         (decrements per score threshold)
// +0x18   int                       currentScore
// +0x3c   HUD*                      pHUD
// +0x44   bool                      isFirstPlay1
// +0x45   bool                      isFirstPlay2
// +0x48   FruitCamera*              pCamera              (0x16c bytes)
// +0x4c   FruitSaveData*            pSaveData            (0x238 bytes)
// +0x50   Font*                     pFont0
// +0x54   Font*                     pFont1
// +0x58   Font*                     pFont2
// +0x5c   Font*                     pFont3
// +0x68   Font*                     pFontOptional
// +0x6c   Font*                     pFontDefault         (fallback/base)
// +0x70   Font*                     pFontRegion[4]       (CJK/Arabic overrides at 0x70/0x74/0x78/0x7c)
// +0x80   Font*                     pFont6
// +0x85   char                      field_0x85
// +0x90   float                     worldPos[3]          (x/y/z)
// +0x9c   char                      flag_0x9c
// +0x9d   char                      flag_0x9d
// +0x9e   char                      flag_0x9e
// +0x17c  SmartPtr<Texture>         pLocalisedTexture    (12 bytes)
// +0x180  int                       field_0x180
// +0x188  GameSound*                pGameSound           (0x708 bytes)
// +0x1a8  char                      flag_0x1a8
// +0x1b1  char                      fruitStats1[256]
// +0x2b1  char                      fruitStats2[256]
// +0x3b1  char                      fruitStats3[256]
// +0x4b1  char                      fruitStats4[256]
// +0x174  int                       fruitTotal           (last AddToTotal result)
// +0x194  int                       m_FrameTimer         (= (int)(dt * scale) + prev; frame counter)
// +0x604  byte                      m_bFrameDirty        (cleared each GameTaskUpdate frame)
// +0xfc   byte                      m_bFieldFc           (= 0 in Game ctor)
// +0xfd   byte                      m_bFieldFd           (= 0 in Game ctor)
// +0x100  int                       m_field100           (= 0 in Game ctor)
//
// Mortar::MortarGame base (size >= 0x1b4):
//   MortarGame ctor zeroes: +0x04..+0x1b3 (via 3 overlapping 64×4 = 256-byte loops)
//   +0xf4  bool   field244_0xf4   (explicitly set false in ctor)
//   MortarGame size is >= 0xfc (Game::Game adds fields at +0xfc, +0xfd, +0x100)
// Game inherits Mortar::MortarGame which inherits from some base.
// Game::Update delegates entirely to GameTaskUpdate(dt).
// GameTaskUpdate uses a task state machine: *Game = current task byte → indexes function table.
//
// HitBomb (0x0016b0fc): on bomb slice in non-Zen mode:
//   1. Game+0x10 = countdown timer (set to game-over delay constant)
//   2. FruitCamera::CreateCameraShake(cam, {a=DAT, b=2.0, c=?}, ...)
//   3. GameTask state struct: +0xcc/0xd0/0xd4 = bomb_pos, +0xf8 = 0
//   4. GameSound::SFXPlay(bomb_hit_sfx)
// In Zen mode bomb hit: AddToCurrentScore(-10, 0, false, false); WaveManager::ResetSpeed; PowerUpManager::ClearTimedPowers
//
// ============================================================
// WaveManager  (size: >= 0x2d8 bytes, singleton)
// ============================================================
// +0x000  Math::Random              random
// +0x0??  vector<WAVE_INFO*>[4]     waveInfoLists        (one per game mode)
// +0x0dc  DEFAULT_WAVE_INFO         defaultWaveInfo[4]   (each 0x40 bytes)
// +0x1dc  COIN_CHANCEINATOR         coinChance[4]        (each 0x08 bytes)
// +0x1fc  vector<PROBABILITY_OVERIDE>[4]  probOverrides
// +0x054  float                     m_Speed[2]           (current wave speed per player; GetSpeed(i) = field_0x54 + i*4)
// +0x068  float                     spawnLevel           (used by Bomb chain spawn)
// +0x070  float                     m_CritChanceMult     (global critical chance multiplier)
// +0x22c  WAVE_INFO*                m_pCurrentWave[2]    (per-player current wave ptr; [0]=+0x22c, [1]=+0x230)
// +0x230  WAVE_INFO*                m_pCurrentWaveP1     (also used as ulong wave-sync token in FruitSlicedPacket)
// +0x2d4  float                     field_0x2d4
//
// CriticalMode(p): GetCriticalChance(p) = m_pCurrentWave[p]->waveInfo[0x64] * m_CritChanceMult
//                  CriticalMode = (Game.m_ScoreThreshold / 2) < criticalChance
// GetCriticalChance returns 1.0 if no active wave
//
// Wave data loaded from XML (TiXmlDocument). 4 game modes throughout.
// WAVE_INFO = 0x78 bytes. DEFAULT_WAVE_INFO = 0x40 bytes.
// SPAWNER_INFO: +0x2c=minAngle, +0x30=maxAngle, +0x34=typeFlags, +0x5c=zOffset
//
// ============================================================
// ScoreModifier : GameModifier  (size: >= 0x3c bytes)
// ============================================================
// +0x00   void*                     vtable
// +0x1c   PowerUp*                  pPowerUp             (inherited from GameModifier)
// +0x20   int                       scoreGainAdd         (flat gain bonus, init=0)
// +0x24   int                       scoreGainMultiply    (gain multiplier, init=1)
// +0x28   int                       scoreLossAdd         (flat loss bonus, init=0)
// +0x2c   int                       scoreLossMultiply    (loss multiplier, init=1)
// +0x30   int                       applyCount           (increments each ApplyModifier call)
// +0x34   bool                      applied              (if true, UpdateSpecific skips)
// +0x38   int                       field_0x38
//
// ============================================================
// MAMAudioThread  (size: >= 0x154 bytes)
// ============================================================
// +0x00   void**                    vtable
// +0x04   int                       field_0x4            (0)
// +0x08   int                       field_0x8            (constant)
// +0x0c   bool                      field_0xc
// +0x0d   bool                      field_0xd
// +0x10   float                     masterVolume         (-1.0f)
// +0x14   int                       field_0x14
// +0x18   int                       sampleRate           (16000 = 16 kHz)
// +0x1c   int                       bufferSize           (0xc80 = 3200)
// +0x20   int                       field_0x20           (0x10a = 266)
// +0x24   int                       field_0x24
// +0x28   int                       field_0x28
// +0x2c   bool                      field_0x2c
// +0x2d   bool                      field_0x2d
// +0x30   int                       voiceCount           (= 16)
// +0x34   MAMVoice                  voices[16]           (each 0x10 bytes = 0x100 total)
// +0x134  NLFQueue<MAMSoundInputCmd>  cmdInput
// +0x144  NLFQueue<MAMSoundOutputCmd> cmdOutput
//
// MAMVoice = 0x10 bytes: +0x00=void*, +0x04=int, +0x08=int, +0x0c=int
//
// ============================================================
// Fruit : Mortar::Entity  (full layout recovered from CollisionResponse)
// ============================================================
// Entity base (size = 0x3c):
// +0x00   EntityFns*                vtable
// +0x0c   byte                      flags
// +0x10   float                     field13_0x10         (pos.x or speed)
// +0x14   float                     field14_0x14         (pos.y or speed)
// +0x18   float                     field15_0x18         (pos.z)
// +0x1c   float                     vel.x
// +0x20   float                     vel.y
// +0x24   float                     vel.z
// +0x36   ushort                    angle
// +0x38   Col*                      m_Col
//
// Fruit own fields (start at +0x3c):
// +0x3c   byte                      m_FruitType          (0..N; × 0x330 for FRUIT_INFO offset)
// +0x3d   char                      m_bFruitFlag3d       (= 0; ≠0 = skip power-up spawn on slice)
// +0x40   PSPParticleEmitter*       m_pEmitter1          (field5_0x40; zeroed in Init)
// +0x44   PSPParticleEmitter*       m_pEmitter2          (field6_0x44; zeroed in Init)
// +0x48   float                     m_SlicePos.x         (copied from entity pos at slice time)
// +0x4c   float                     m_SlicePos.y
// +0x50   float                     m_SlicePos.z
// +0x60   int                       m_field60            (= 0 in Init)
// +0x64   int                       m_CollisionSize      (= 75 = 0x4b in Init; collision circle radius or half-size)
// +0x68   int                       m_field68            (= 4 in Init)
// +0x6c   float                     m_SliceSpeedMult     (init=-1.0f; normal slice=×2.5, critical=×0.5)
// +0x70   ushort                    m_SliceAngle         (Atan2Idx(blade.x, blade.y))
// +0x74   float                     m_SliceImpulse       (clamp 4–8; or 6–8 for special)
// +0x78   int                       m_SliceState         (= 0 in Init; set on slice)
// +0x7c   byte                      m_bActive            (= 1 in Init)
// +0x80   float                     m_field80            (= DAT in Init)
// +0x84   float                     m_RotAxisX           (from global config vec3[0])
// +0x88   float                     m_RotAxisY           (from global config vec3[1])
// +0x8c   float                     m_RotAxisZ           (from global config vec3[2])
// +0x90   int                       m_PlayerIdx          (= 0 in Init; set for multiplayer routing)
// +0x94   float                     m_field94            (= 1.0f in Init)
// +0x98   float                     m_ZPosition          (from GetFruitZPosition())
// +0x9c   float                     m_HalfA_StartPos.x   (init = DAT; off-screen spawn for half A)
// +0xa0   float                     m_HalfA_StartPos.y   (init = -12.0f = below screen)
// +0xa4   float                     m_HalfA_StartPos.z   (init = DAT)
// +0xb4   char                      m_bSliced            (= 0 in Init; guard in CollisionResponse)
// +0xb8   float                     m_SecondPos.x        (second particle emitter position)
// +0xbc   float                     m_SecondPos.y
// +0xc0   float                     m_SecondPos.z
// +0xd0   _Quaternion<float>        m_Rot1               (16 bytes; both halves init from RandomStartAngle)
// +0xe0   _Quaternion<float>        m_Rot2               (16 bytes)
// +0xf0   Vec3                      m_RotVel1            (random [-5.5, 5.5] per component)
// +0xfc   Vec3                      m_RotVel2            (random [-5.5, 5.5] per component)
// +0x108  int                       field169_0x108       (= 0 in Init)
// +0x10c  int                       m_field10c           (= 0 in Init)
// +0x10d  byte                      m_bCriticalEligible  (= 1 in Init; = 0 after critical slice)
// +0x110  int                       m_field110           (= DAT in Init)
// +0x114  int                       m_field114           (= 0 in Init)
//
// FRUIT_INFO struct size = 0x330 (816 bytes). Accessed as fruit_type × 0x330:
//   +0x250 = particleEmitterHash (ulong)
//   +0x25c = particleEmitterHash2 (ulong)
//   +0x314 = int (value 0x32=50 triggers critical impulse range 6–8)
//   +0x318 = char (flag for combo critical check)
//   +0x31c = char* soundList (pointer)
//   +0x320 = int soundCount
//   +0x328 = int FruitInfo::field766 (for coin spawn check)
//   +0x32c = int hasPowerUp (non-zero → spawn power-up on slice)
//
// Key methods:
//   Slice             (0x176d58)   — called to initiate slicing (sets up trajectory)
//   Update            (0x176770)   — physics integration + Col update
//   Chuck             (0x175a64)   — throw/launch the fruit
//   Init              (0x176708)
//   KillFruit         (0x176abc)
//   CollisionResponse (0x1780b0)   — triggered by SlashEntity; does actual slice logic:
//                                   1. Check m_bSliced guard
//                                   2. Critical hit probability check
//                                   3. Play SFX (normal or critical)
//                                   4. Capture slice angle/impulse from blade velocity
//                                   5. Spawn juice particles (PSPParticleManager)
//                                   6. AddSlice() for visual effect
//                                   7. UnlockSpecificOrderAchievement
//                                   8. Optional: PowerUpManager::RandomPower() if hasPowerUp
//   Sliced() const    — returns m_bSliced
//   IsActive() const  — active entity check
//
// ============================================================
// Bomb : Mortar::Entity
// ============================================================
// +0x00   EntityFns*                vtable
// +0x1c   float                     pos.x
// +0x20   float                     pos.y
// +0x24   float                     pos.z
// +0x??   Col*                      m_Col
// +0x40   Delegate0<void>           hitCallback
// +0x64   int                       field38_0x64
// +0x68   char                      activeFlag           (controls update branch)
// +0x7c   int                       field58_0x7c
// +0x80   char                      movementFlag
// +0x84   int                       field63_0x84
// +0x8c   Vector3                   accelForce
// +0xa4   float                     countdown            (timer, triggers chain spawn)
// +0xa8   float                     speedMult
//
// Key methods: Update (0x1729fc), Init (0x172504), Draw (0x171be8),
//              CollisionResponse (0x17280c), Chuck (0x170f68)
// Countdown triggers WaveManager::SpawnBomb(count-1) for chain bombs
//
// ============================================================
// ItemManager  (singleton)
// ============================================================
// +0x00   ItemInfo*                 defaultItem[4]       (first item per type)
// +0x10   vector<ItemInfo*>         allItems             (12 bytes)
// +0x1c   map<ulong,ItemInfo*>      itemById             (24 bytes)
// +0x34   map<ulong,ItemInfo*>      itemsByType[4]       (each 24 bytes, at 0x34/0x4c/0x64/0x7c)
//
// ItemInfo (0x40 bytes): +0x08=ulong key, +0x0c=int achieveId(-1=free), +0x10=type, +0x3c=newFlag
// SlashModInfo extends ItemInfo (0x110 bytes)
//
// ============================================================
// FruitSaveData  (size: 0x238 = 568 bytes)
// ============================================================
// +0x00   map<ulong,SliceTotal>     sliceTotals1         (24 bytes)
// +0x18   map<ulong,SliceTotal>     sliceTotals2         (24 bytes)
// +0x34   list<EntityState>         entityStates         (12 bytes)
// +0x44   int                       perModeField[4]      (at 0x44/0x48/0x4c/0x50)
// +0x54   int                       perModeField2[4]     (at 0x54/0x58/0x5c/0x60)
// +0x64   int                       field73_0x64
// +0x68   int                       field74_0x68
// +0x6c   int                       field75_0x6c         (copied to Game+0x04 as gameMode)
// +0x74   int                       field80_0x74         (= 0xffffffff)
// +0x78   int                       highscore            (named by symbols!)
// +0x7c   int                       field82_0x7c
// +0x80   int                       perTypeData[32]      (= 0xffffffff each)
// +0x10c  float                     field214             (-1.0f)
// +0x114  int                       field216             (0xffffffff)
// +0x118  float                     field217             (-1.0f)
// +0x11c  int                       field218             (0xffffffff)
// +0x120  int                       field219             (0xffffffff)
// +0x124  int                       field220             (0xffffffff)
// +0x128  int                       field221             (0xffffffff)
// +0x12c  bool                      field_0x12c
// +0x12d  bool                      field_0x12d
// +0x130  float                     field226
// +0x134  float                     field227             (-1.0f)
// +0x138  float                     m_blitzSpawnTime
// +0x13c  float                     field229             (1.0f)
// +0x14c  float                     field233             (1.0f)
// +0x150  list<WaveState>           waveStates           (12 bytes)
// +0x158  map<ulong,AchievementItem> achievements1       (24 bytes)
// +0x170  map<ulong,AchievementItem> achievements2       (24 bytes)
// +0x194  map<int,int>              scoreMaps[4]         (per game mode, each 24 bytes)
// +0x1f8  int                       perModeField3[4]
//         float                     m_WaveWait
//         float                     m_WaveDelay
//         int                       m_WaveCount
//         byte                      m_CriticalChance     (= 0x46 = 70%)
//         int                       m_blitzSpawnedThisGame
//         int                       m_blitzForceSpawnedCounter
//
// ============================================================
// SlashEntity : Mortar::Entity  (blade/swipe collision, size >= 0x184)
// ============================================================
// Entity base ends at ~0x3c; SlashEntity fields follow.
//
// +0x00   EntityFns*                vtable               (via Entity)
// +0x0c   byte                      flags                (|= 2 when blade active)
// +0x36   ushort                    angle                (updated from m_AngleCopy each frame)
// +0x38   ColLine*                  m_Col                (line segment, 0x20 bytes)
//         -- SlashEntity own fields --
// +0x3c   PSPParticleEmitter*       m_TrailEmitter       (touch trail particle, null when inactive)
// +0x40   float                     m_Scale              (init = DAT_0017c760)
// +0x44   Colour                    m_BaseColour         (RGBA, 4 bytes)
// +0x48   Colour                    m_HighlightColour    (RGBA, 4 bytes)
// +0x4c   char                      m_bFlag4c            (init = 0)
// +0x50   int                       m_SplitPoint         (split index for same-screen multiplayer)
// +0x58   int                       m_PointCount         (blade trail vertex count, 4 = min for collision)
// +0x5c   void*                     m_pLeftBuffer        (ptr to left/top vertex strip)
// +0x60   void*                     m_pRightBuffer       (ptr to right/bottom vertex strip)
// +0x64   float                     m_BladeDir.x         (blade velocity direction, normalised)
// +0x68   float                     m_BladeDir.y
// +0x6c   float                     m_BladeDir.z
// +0x70   float                     m_TailPos.x          (oldest visible trail point)
// +0x74   float                     m_TailPos.y
// +0x78   float                     m_TailPos.z
// +0x7c   float                     m_HeadPos.x          (newest trail point / current tip)
// +0x80   float                     m_HeadPos.y
// +0x84   float                     m_HeadPos.z
// +0x94   float                     m_LineLengthSq       (= |head-tail|^2; -1.0 = no active segment)
// +0x98   float                     m_SpeedScale         (blade speed multiplier)
// +0x9c   int                       m_SliceCount         (incremented +2 per slice; low bits = ?)
// +0xa0   float                     m_SliceTimerA        (zeroed on each slice)
// +0xa4   float                     m_SliceTimerB        (zeroed on each slice)
// +0xa8   float                     m_BladeVelAtSlice.x  (blade dir snapshot at moment of slice)
// +0xac   float                     m_BladeVelAtSlice.y
// +0xb0   float                     m_BladeVelAtSlice.z
// +0xb4   float                     m_SlicePos.x         (world position of sliced entity)
// +0xb8   float                     m_SlicePos.y
// +0xbc   float                     m_SlicePos.z
// +0xc0   int                       m_SliceEntityType    (byte from entity; score accumulator)
// +0xc4   float                     m_ScoreBonus         (score multiplier field)
// +0xc8   Vec3                      m_GhostPositions[6]  (6 × 12 = 72 bytes; ends at +0x110)
// +0x110  int                       m_GhostCount         (init = 0)
// +0x114  int                       m_GhostFlags         (init = 0)
// +0x118  Vec3                      m_GhostDir           (direction snapshot for ghost)
// +0x124  float                     m_ComboTimer         (time window for combo; reset on slice)
// +0x128  int                       m_ComboCount         (fruits sliced in current combo)
// +0x12c  int                       m_ComboEntityType    (0=fruit, 1=bomb, 2=special)
// +0x130  MissControl*              m_pComboCtrl         (null if no active combo)
// +0x134  float                     m_GhostTimer         (counts up while m_bGhostActive)
// +0x138  char                      m_bGhostActive       (if true, timer runs -> CreateGhost())
// +0x13c  int                       m_ColEntityA         (collision entity handle; -1 = none)
// +0x140  int                       m_ColEntityB         (collision entity handle; -1 = none)
// +0x144  char                      m_bBladeActive       (true = blade is a valid collision line)
// +0x148  float                     m_ComboScoreBase     (6.0f; decremented (combo_n * 0.75) per slice)
// +0x14c  int                       m_ExtraFieldA        (init = -1)
// +0x150  int                       m_ExtraFieldB        (init = -1)
// +0x154  int                       m_ComboFruitIDs[11]  (11 × 4 = 0x2c bytes; end at +0x180)
// +0x180  ushort                    m_AngleCopy          (updated each frame; copied to Entity::angle)
//
// ColLine  (size: 0x20 bytes):
//   +0x00  ColFns*  vtable
//   +0x04  float    a.x   (endpoint A)
//   +0x08  float    a.y
//   +0x0c  float    a.z
//   +0x10  float    b.x   (endpoint B; overlaps Col[1].vtable slot)
//   +0x14  float    b.y
//   +0x18  float    b.z
//   +0x1c  (pad)
//
// ColCircle / fruit collision shape:
//   m_Col[0]: {vtable, cx, cy, cz}    -- center point
//   m_Col[1]: {radius_as_ptr, ?, ?, ?} -- radius stored in field0_0x0 slot
//   vtable->GetType() returns 1 for circle.
//
// Collision: blade segment vs circle = segment-circle intersection.
// Returns 1 if any point on segment within radius of circle center.
//
// Key methods:
//   Init              (0x0017c65c)  -- allocates ColLine, calls InitPoints(0xa0)
//   InitPoints        (0x0017c340)  -- sets up vertex buffers (0xa0 bytes each)
//   UpdatePoints      (0x0017b92c)  -- rebuilds vertex strips from trail, computes angle
//   UpdateTouchDown   (0x0017d2e4)  -- manages trail particle emitter on touch
//   Update            (0x0017d664)  -- iterates entities, calls CollideWithEntity
//   CollideWithEntity (0x0017b570)  -- line-vs-circle test (see above)
//   CreateGhost       (0x0017b82c)  -- spawns SlashEntityGhost for visual echo
//   DrawSlice         (0x0017e424)  -- renders blade geometry
//   PreDraw           (0x0017e504)
//
// ============================================================
// Mortar::Entity base layout (size = 0x3c)
// ============================================================
// +0x00   EntityFns*                vtable
// +0x04   int                       field_0x04
// +0x08   ushort                    m_TrackerID          (entity network tracker ID; used in FruitSlicedPacket)
// +0x0a   (2 bytes padding)
// +0x0c   byte                      flags                (bit 1 = has collision shape)
// +0x10   float                     field13_0x10         (pos.x or spawn speed X)
// +0x14   float                     field14_0x14         (pos.y or spawn speed Y)
// +0x18   float                     field15_0x18         (pos.z)
// +0x1c   float                     field16_0x1c         (vel.x)
// +0x20   float                     vel.y
// +0x24   float                     vel.z
// +0x36   ushort                    angle                (blade/rot angle; CosIdx/SinIdx)
// +0x38   Col*                      m_Col                (collision shape pointer)
//
// Game+0x04  = byte gameMode (0=Classic, 1=Arcade, 2=Zen/ZenBlitz, 3=TBD)
// Game+0x05  = byte pauseFlag
// Game+0x06  = byte gameStateFlag (=0 checks for offscreen bonus logic)
// Game+0x1c  = byte m_bUnsullied (= 0 = no misses yet; checked for UnsulliedAchievement)
// Game+0x30  = int  m_ScoreThreshold (decremented on fruit slice, used for score-tier SFX)
//
// ============================================================
// Mortar::MortarCamera  (size: 0x12c)
// ============================================================
// +0x000  MortarCameraFns*          fns                  (vtable-like function ptr)
// +0x004  Matrix43                  m_localToWorld       (4×3 = 48 bytes, ends at 0x34)
// +0x034  Matrix44                  m_projection         (4×4 = 64 bytes, ends at 0x74)
// +0x074  Matrix43                  m_viewMatrix         (4×3 = 48 bytes, ends at 0xa4)
// +0x0a4  Matrix44                  m_field4             (4×4 = 64 bytes, ends at 0xe4)
// +0x0e4  Vec3                      m_pos                (camera world position)
// +0x0f0  Vec3                      m_lookAt             (look-at target point)
// +0x0fc  Vec3                      m_up                 (up vector)
// +0x108  byte                      m_bDirty             (= 1 when pos/lookAt changed)
// +0x109  byte                      field_0x109          (= 1 after Init)
// +0x10c  Vec3                      field12_0x10c        (frustum / clip data)
// +0x118  float                     field15_0x118
// +0x11c  float                     m_nearX              (Init param3 = near-plane X angle)
// +0x120  float                     m_nearY              (Init param4 = near-plane Y angle)
// +0x124  float                     m_fovOrNear          (Init param1; default = 1.0f)
// +0x128  float                     m_farPlane           (Init param2)
//
// ============================================================
// FruitCamera : Mortar::MortarCamera  (size: 0x16c)
// ============================================================
// MortarCamera base = 0x12c bytes; FruitCamera fields follow.
//
// +0x12c  MortarCameraFns*          m_pFollowFns         (null = idle, non-null = follow mode)
// +0x130  int                       m_CameraMode         (0 = idle; 1 = follow; decompiler shows as float ~1e-45)
// +0x134  ushort                    m_field3_0x134       (cast to float for +0x150)
// +0x136  ushort                    m_field4_0x136       (cast to float for +0x14c)
// +0x138  float                     m_ShakeDir.x         (Vec2 shake direction)
// +0x13c  float                     m_ShakeDir.y
// +0x140  ushort                    m_ShakeAngle         (Atan2Idx result from CreateCameraShake)
// +0x142  (2 bytes padding)
// +0x144  float                     m_TargetX            (follow target X, init from data ptr)
// +0x148  float                     m_TargetY            (follow target Y)
// +0x14c  float                     m_field14c           (= (float)m_field4_0x136 each UpdateCamera)
// +0x150  float                     m_field150           (= (float)m_field3_0x134)
// +0x154  float                     m_DistanceMag        (|pos - someTarget| magnitude)
// +0x158  float                     m_LookAtSnapshot.x   (lookAt saved each UpdateCamera)
// +0x15c  float                     m_LookAtSnapshot.y
// +0x160  float                     m_LookAtSnapshot.z
// +0x164  float                     m_ShakeIntensity     (shake amplitude; init = DAT_00180e30)
// +0x168  MortarCameraFns*          m_field168           (set from param_1 in CreateCameraShake)
//
// UpdateCamera dispatch: m_CameraMode==0 → UpdateIdle; 1 → UpdateFollow
// CreateCameraShake: computes shake direction from impact Vec3, scales by velocity
//
// Key methods:
//   FruitCamera        (0x00180de0)  ctor
//   UpdateCamera       (0x00180c8c)
//   UpdateShake        (0x00180ea0)
//   CreateCameraShake  (0x00180d10)
//   SetupPerspective   (0x001810ac)
//   FollowEntity       (0x00180b2c)
//
// ============================================================
// Asset loading order (GameInitialise)
// ============================================================
// 1. MenuButton::LoadContent
// 2. Fruit::LoadInfo
// 3. SplatEntity::LoadContent
// 4. SlashEntity::LoadContent
// 5. Bomb::LoadContent
// 6. GameOverScreen::LoadContent
// 7. PowerUpShop::LoadContent
// 8. PreloadSounds
//
// ============================================================
// HUD  (size: ~0x20)
// ============================================================
// +0x00  list<HUDControl*>         controls             (std::list = 8 bytes on this ABI)
// +0x08  float                     field1_0x8           (init = 1.0f)
// +0x0c  float                     field2_0xc           (init = 1.0f)
// +0x10  float                     field3_0x10          (init = 1.0f)
// +0x14  float                     field4_0x14          (init = 1.0f)
// +0x18  float                     field5_0x18          (init = 1.0f)
// +0x1c  float                     field6_0x1c          (init = 1.0f)
//
// Update: calls MissControl::PreUpdate, iterates controls list; removes controls with field_0x33 set.
//
// ============================================================
// HUDControl  (base class, used by MissControl, TimeControl, SpeedControl, TutorialControl…)
// ============================================================
// +0x00  HUDControlFns*            vtable
// +0x08  float                     pos.x
// +0x0c  float                     pos.y
// +0x10  float                     pos.z
// +0x20  float                     size.x               (half-extents, used for clamping to screen)
// +0x24  float                     size.y
// +0x28  float                     size.z
// +0x2c  float                     field_0x2c           (timer or alpha)
// +0x30  int                       m_bActive            (non-zero = active)
// +0x32  char                      m_bNoDestructor      (= 0 → call dtor on removal)
// +0x33  char                      m_bPendingRemoval    (set → remove next HUD::Update)
// +0x34  int                       field49_0x34         (= 1 after init)
// +0x38  Delegate1<void,HUDControl*> m_RemoveCallback   (called before removal)
// +0x5f  byte                      m_Alpha              (= 0xff = fully opaque)
//
// vtable[0x0a]=Update, vtable[0x0c]=active_check, vtable[0x28]=Update(float)
//
// ============================================================
// MissControl : HUDControl3d : HUDControl  (combo text display)
// ============================================================
// HUDControl size = ?; MissControl own fields at ~+0x7c
//
// +0x7c  byte                      m_AnimState          (0=idle, 3=animating)
// +0x7d  byte                      m_bVisible           (= 1 after MakeCombo)
// +0x7e  ushort                    field_0x7e           (= 0)
// +0x80  float                     field5_0x80          (fade alpha scale)
// +0x84  byte                      m_bActive            (= 1 = combo display active)
// +0x85  byte                      m_bFlag              (= 1 in MakeCombo)
// +0x88  int                       m_ComboCount         (number of fruits in combo)
// +0x8c  byte                      m_bFlag8c            (= 1 in Init)
// +0x90  float                     field15_0x90         (= 1.0f)
//
// Pool: up to 9 combo text sprites (digit textures 1..9 loaded in ctor).
// MakeCombo(pos, comboCount, entityType): selects digit texture, animates bounce.
// GetFree (0x00150da4): scans pool for inactive instance.
//
// ============================================================
// PowerUpManager  (singleton, partial)
// ============================================================
// +0x60  int                       m_field60            (= 0 after SetDefaults)
// +0x64  float                     m_DtMod              (dt multiplier; ApplyDtMod multiplies this)
// +0x68  float                     m_field68            (= DAT after SetDefaults)
// +0x6c  float                     m_field6c            (= 1.0f)
// +0x70  float                     m_field70            (= 1.0f)
// +0x78  int                       m_ScoreGainMult      (used by GetScoreGainMultiplier)
// +0x7c  int                       m_ScoreGainFactor    (multiplied with above)
// +0x88  float                     m_field88            (= DAT after SetDefaults)
//
// ApplyDtMod: m_DtMod *= param_1 (used for time-scale power-ups)
// SlashEntity::Update checks m_DtMod against threshold to scale blade speed.
//
// ============================================================
// BonusManager  (singleton, size ~0x20)
// ============================================================
// +0x00  vector<BonusType>         bonusTypes           (12 bytes)
// +0x0c  list<Bonus>               m_field12_0xc        (12 bytes)
// +0x14  vector<int>               m_field_0x14         (12 bytes)
//
// ============================================================
// Subsystem singletons
// ============================================================
// SystemManager, MatrixManager, FileManager, DisplayManager (320x480)
// TextureManager, MeshManager, AnimationManager, InputManager
// PSPParticleManager, PowerUpManager, LeaderboardManager
// NetworkManager (P2P + OpenFeint + GameCenter)
// MAMAudioController -> MAMAudioThread (16 voices, 16kHz)
// WaveManager, ItemManager, AchievementManager, BonusManager
// Mortar::Touch, Mortar::SoundManager, FruitCamera
//
// ============================================================
// FRUIT_INFO  (size: 0x330 = 816 bytes)
// ============================================================
// Array of these indexed by fruit_type byte (Fruit.m_FruitType × 0x330).
//
// +0x140  char*                     m_StatCategoryName   (for FruitSaveData::AddToTotal stat key)
// +0x250  ulong                     m_ParticleHashA      (hash for juice particle emitter A)
// +0x25c  ulong                     m_ParticleHashB      (hash for second particle emitter)
// +0x260  ulong                     m_AchievementHash    (for UnlockConsecutiveAchievement)
// +0x314  int                       m_BaseScore          (points awarded on normal slice; 0x32=50)
// +0x318  char                      m_bComboFlag         (non-zero = eligible for critical combo check)
// +0x31c  char*                     m_SoundList          (ptr to array of SFX name strings)
// +0x320  int                       m_SoundCount         (number of SFX strings in list)
// +0x324  int                       m_RandBonusBase      (random bonus range start)
// +0x328  int                       m_RandBonusMax       (random bonus range max; 0 = no random bonus)
// +0x32c  int                       m_bHasPowerUp        (non-zero → PowerUpManager::RandomPower on slice)
//
// ============================================================
// FruitSlicedPacket  (network sync packet)
// ============================================================
// Constructed with: waveNumber, entityTrackerID, rotation (ushort), magnitude (float), points (int)
// Sent via NetworkManager on each online multiplayer fruit slice.
// Also used for Bomb slices (FruitSlicedPacket variant).
//
// ============================================================
// Scoring pipeline summary
// ============================================================
// 1. SlashEntity::Update → iterates Fruit/Bomb entities via ActorManager
// 2. For each: SlashEntity::CollideWithEntity (line–circle segment test)
// 3. On hit: entity->vtable->CollisionResponse(entity, slash, 0, 0, &bladeVel)
// 4. Fruit::CollisionResponse:
//    a. Check critical probability (Game.m_ScoreThreshold / WaveManager::GetCriticalChance)
//    b. Play SFX, spawn juice particles, AddSlice() visual
//    c. Compute points: base = FRUIT_INFO.m_BaseScore; critical += bonus
//    d. AddToCurrentScore(points, playerIdx, true, false)
//    e. WaveManager::AddSpeed in Zen mode
//    f. FruitSaveData tracking (per-fruit stats, achievements)
//    g. AchievementManager checks
// 5. AddToCurrentScore:
//    a. Apply GetScoreMultiplyer * delegate modifier
//    b. Add to Game.m_CurrentScore (+0x18)
//    c. Decrement Game.m_ScoreThreshold (+0x30) on tier crossing → play SFX
//    d. FruitSaveData::AddToTotal for stat tracking
// 6. SlashEntity combo scoring (triggered on timer expiry):
//    a. Decrement Game.m_ScoreThreshold
//    b. AddToCurrentScore(comboCount, entityType, true, ...)
//    c. BonusManager::AddCombo in Zen mode
//    d. Coin::MakeCoins for coin rewards
//
// @author Claude (GhidraMCP RE session)
