#!/usr/bin/env python3
"""Detect function signature mismatches between binary and port.

A signature mismatch means the port has a function with the same Class::Method
name but different parameter types/count — producing a different mangled name
that asm-verify never compares (the binary symbol falls into "binary-only"
and the port symbol into "port-only"). These are invisible to asm-verify
diffing but may represent real bugs.

Usage:
    python tools/asm-verify/check-signatures.py

Reads tmp/symbol-diff/binary_symbols_demangled.txt and
tmp/symbol-diff/port_full_demangled.txt (generated by the symbol-diff skill).
Outputs a report to tmp/asm-verify/signature-mismatches.md.
"""
import pathlib
import re
import sys
from collections import defaultdict

PROJECT = pathlib.Path(__file__).resolve().parent.parent.parent

BINARY_DEMANGLED = PROJECT / "tmp" / "symbol-diff" / "binary_symbols_demangled.txt"
PORT_DEMANGLED    = PROJECT / "tmp" / "symbol-diff" / "port_full_demangled.txt"
OUTPUT = PROJECT / "tmp" / "asm-verify" / "signature-mismatches.md"

# Known intentional signature divergences — port faithfully adapts binary's
# opaque pointer/reference patterns into typed equivalents. These are NOT
# signature bugs; they are documented // Port-specific: refactorings.
KNOWN_SIGNATURE_ALIASES = {
    # Binary: Draw(float*) passes a Vec3* HUD scale as opaque float pointer.
    # Port:   Draw(Vec3 const&, int) types the scale + formalizes the layer
    #         mask that flows through from DrawOrder's vtable dispatch in r2.
    # RE confirmed v1.6.1: float* is Vec3* HUD scale, int is implicit reg.
    # Applies to: CheckBox, BonusScreen, AboutScreen, MainScreen, PauseScreen,
    # ShopScreen, DojoScreen, GameOverScreen, GameModeScreen, MissControl,
    # ProgressionTimerControl, and any other HUDControl subclass.
    ('::Draw', 'float*', '_Vector3<float> const&, int'),
    ('::Draw', 'float*', 'Renderer&'),
    # Binary: PreDraw(float*) passes Vec3* HUD scale.
    # Port:   PreDraw(Vec3 const&) types it. Same reasoning as Draw.
    ('::PreDraw', 'float*', '_Vector3<float> const&'),
}

def method_key(demangled: str) -> str | None:
    """Extract 'Class::Method' (without params) from a demangled symbol."""
    # Strip leading return type: "void Foo::bar(...)" -> "Foo::bar(...)"
    m = re.match(r'^(?:.*\s+)?(\w+(?:::[\w~]+)+)\s*\(', demangled)
    return m.group(1) if m else None

def param_sig(demangled: str) -> str | None:
    """Extract parameter list from demangled symbol."""
    m = re.search(r'\((.*)\)', demangled)
    return m.group(1) if m else None

def load_demangled(path: pathlib.Path) -> set[str]:
    if not path.exists():
        print(f"ERROR: {path} not found. Run symbol-diff skill first.", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding='utf-8', errors='ignore') as f:
        return {line.strip() for line in f if line.strip() and not line.startswith('#')}

def _is_known_alias(method: str, bin_params: str, port_params: str) -> bool:
    """Check if a signature mismatch matches a known intentional divergence."""
    for suffix, bin_pat, port_pat in KNOWN_SIGNATURE_ALIASES:
        if method.endswith(suffix) and bin_pat in bin_params and port_pat in port_params:
            return True
    return False


def main():
    binary = load_demangled(BINARY_DEMANGLED)
    port   = load_demangled(PORT_DEMANGLED)

    # Build port method-key index: key -> list of full signatures
    port_keys: dict[str, list[str]] = defaultdict(list)
    for s in port:
        k = method_key(s)
        if k:
            port_keys[k].append(s)

    # Find binary symbols whose method key exists in port (different mangled name!)
    mismatches: list[tuple[str, str, str]] = []  # (key, binary_sig, port_sig)
    filtered_count = 0
    port_only_with_binary_key: dict[str, list[str]] = defaultdict(list)

    binary_keys = set()
    for s in binary:
        k = method_key(s)
        if k:
            binary_keys.add(k)
            if k in port_keys:
                # Potential mismatch: same method name in both, but different mangling
                b_params = param_sig(s) or "?"
                # Find port signatures for this key (could be multiple overloads)
                for ps in port_keys[k]:
                    p_params = param_sig(ps) or "?"
                    if b_params != p_params:  # different parameters = signature mismatch
                        # Filter: skip known intentional signature aliases
                        if _is_known_alias(k, b_params, p_params):
                            filtered_count += 1
                            continue
                        mismatches.append((k, b_params, p_params))

    # Also find port-only symbols whose key exists in binary (potentially wrong param)
    for s in port:
        k = method_key(s)
        if k and k in binary_keys:
            # Port has a function whose name exists in binary
            already_flagged = any(k == mk for mk, _, _ in mismatches)
            if not already_flagged:
                # Check if binary has a matching signature
                binary_has_match = False
                for bs in binary:
                    if method_key(bs) == k and param_sig(bs) == param_sig(s):
                        binary_has_match = True
                        break
                if not binary_has_match:
                    p_params = param_sig(s) or "?"
                    # Find binary params for the same key
                    b_params = next((param_sig(bs) for bs in binary if method_key(bs) == k), "?")
                    mismatches.append((k, b_params, p_params))

    # Group by class
    by_class: dict[str, list] = defaultdict(list)
    for key, b_params, p_params in mismatches:
        cls = key.rsplit('::', 1)[0] if '::' in key else key
        by_class[cls].append((key, b_params, p_params))

    # Write report
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write("# Signature Mismatches: Binary vs Port\n\n")
        f.write(f"- Binary symbols: **{len(binary)}**\n")
        f.write(f"- Port symbols: **{len(port)}**\n")
        f.write(f"- Signature mismatches: **{len(mismatches)}**\n")
        f.write(f"- Filtered (known intentional): **{filtered_count}**\n\n")
        f.write("Functions where Class::Method names match but parameter types differ.\n")
        f.write("These are INVISIBLE to asm-verify (different mangled names → never compared).\n")
        f.write("Filtered entries are known // Port-specific: refactorings (e.g. Draw(float*)→Draw(Vec3&,int)).\n\n")

        for cls in sorted(by_class):
            items = by_class[cls]
            f.write(f"## {cls} ({len(items)} mismatch{'es' if len(items)>1 else ''})\n\n")
            f.write("| Method | Binary params | Port params |\n")
            f.write("|--------|--------------|-------------|\n")
            for method, b_params, p_params in sorted(items):
                # Truncate long param lists
                bp = b_params[:80] + '...' if len(b_params) > 80 else b_params
                pp = p_params[:80] + '...' if len(p_params) > 80 else p_params
                f.write(f"| `{method}` | `{bp}` | `{pp}` |\n")
            f.write("\n")

    print(f"Found {len(mismatches)} signature mismatches in {len(by_class)} classes ({filtered_count} filtered as known intentional)")
    for cls in sorted(by_class)[:10]:
        print(f"  {cls}: {len(by_class[cls])} mismatch(es)")
    print(f"\nFull report: {OUTPUT}")

if __name__ == '__main__':
    main()
